cc_test(
    name = "test_async_logger",
    srcs = [
        "test_async_logger.cc",
    ],
    deps = [
        "//src:cppev",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "test_buffer",
    srcs = [
        "test_buffer.cc",
    ],
    deps = [
        "//src:cppev",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "test_common_utils",
    srcs = [
        "test_common_utils.cc",
    ],
    deps = [
        "//src:cppev",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "test_ipc",
    srcs = [
        "test_ipc.cc",
    ],
    deps = [
        "//src:cppev",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "test_timer",
    srcs = [
        "test_timer.cc",
    ],
    deps = [
        "//src:cppev",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "test_lru_cache",
    srcs = [
        "test_lru_cache.cc",
    ],
    deps = [
        "//src:cppev",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "test_nio_evlp",
    srcs = [
        "test_nio_evlp.cc",
    ],
    deps = [
        "//src:cppev",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "test_lock",
    srcs = [
        "test_lock.cc",
    ],
    deps = [
        "//src:cppev",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "test_subprocess",
    srcs = [
        "test_subprocess.cc",
    ],
    deps = [
        "//src:cppev",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "test_thread_pool",
    srcs = [
        "test_thread_pool.cc",
    ],
    deps = [
        "//src:cppev",
        "@googletest//:gtest_main",
    ],
)
