cc_library(
    name = "lib",
    hdrs = [
        "config.h",
    ],
)

cc_binary(
    name = "tcp_client",
    srcs = [
        "config.h",
        "tcp_client.cc"
    ],
    deps = [
        "//src:cppev",
    ]
)

cc_binary(
    name = "tcp_server",
    srcs = [
        "config.h",
        "tcp_server.cc"
    ],
    deps = [
        "//src:cppev",
    ]
)

cc_binary(
    name = "udp_client",
    srcs = [
        "config.h",
        "udp_client.cc"
    ],
    deps = [
        "//src:cppev",
    ]
)

cc_binary(
    name = "udp_server",
    srcs = [
        "config.h",
        "udp_server.cc"
    ],
    deps = [
        "//src:cppev",
    ]
)
