cc_binary(
    name = "file_transfer_client",
    srcs = [
        "config.h",
        "file_transfer_client.cc",
    ],
    deps = [
        "//src:cppev",
    ],
)

cc_binary(
    name = "file_transfer_server",
    srcs = [
        "config.h",
        "file_transfer_server.cc",
    ],
    deps = [
        "//src:cppev",
    ],
)
