load("//bztools:package.bzl", "package_files")

package_files(
    name = "cppev_examples",
    files = [
        "//examples/tcp_stress:simple_server",
        "//examples/tcp_stress:simple_client",
        "//examples/file_transfer:file_transfer_server",
        "//examples/file_transfer:file_transfer_client",
    ],
)
