cc_binary(
    name = "simple_client",
    srcs = [
        "config.h",
        "simple_client.cc",
    ],
    deps = [
        "//src:cppev",
    ],
    visibility = [
        "//examples:__pkg__",
    ],
)

cc_binary(
    name = "simple_server",
    srcs = [
        "config.h",
        "simple_server.cc",
    ],
    deps = [
        "//src:cppev",
    ],
    visibility = [
        "//examples:__pkg__",
    ],
)
